<?$APPLICATION->IncludeComponent(
    "bitrix:sale.recommended.products",
    "sale-recomm-product",
    Array(
        "ACTION_VARIABLE" => "action",
        "ADDITIONAL_PICT_PROP_10" => "MORE_PHOTO",
        "ADDITIONAL_PICT_PROP_11" => "MORE_PHOTO",
        "ADDITIONAL_PICT_PROP_12" => "MORE_PHOTO",
        "ADD_PROPERTIES_TO_BASKET" => "Y",
        "BASKET_URL" => "/personal/basket.php",
        "CACHE_TIME" => "86400",
        "CACHE_TYPE" => "A",
        "CART_PROPERTIES_10" => array("",""),
        "CART_PROPERTIES_11" => array("",""),
        "CART_PROPERTIES_12" => array("",""),
        "CODE" => "",
        "CONVERT_CURRENCY" => "N",
        "DETAIL_URL" => "",
        "HIDE_NOT_AVAILABLE" => "N",
        "IBLOCK_ID" => "21",
        "IBLOCK_TYPE" => "1c_catalog",
        "ID" => $arResult['ID'],
        "LABEL_PROP_10" => "-",
        "LABEL_PROP_11" => "-",
        "LINE_ELEMENT_COUNT" => "3",
        "MESS_BTN_BUY" => "РљСѓРїРёС‚СЊ",
        "MESS_BTN_DETAIL" => "РџРѕРґСЂРѕР±РЅРµРµ",
        "MESS_BTN_SUBSCRIBE" => "РџРѕРґРїРёСЃР°С‚СЊСЃСЏ",
        "MESS_NOT_AVAILABLE" => "РќРµС‚ РІ РЅР°Р»РёС‡РёРё",
        "MIN_BUYES" => "1",
        "OFFER_TREE_PROPS_12" => array(),
        "PAGE_ELEMENT_COUNT" => "30",
        "PARTIAL_PRODUCT_PROPERTIES" => "N",
        "PRICE_CODE" => array(),
        "PRICE_VAT_INCLUDE" => "Y",
        "PRODUCT_ID_VARIABLE" => "id",
        "PRODUCT_PROPS_VARIABLE" => "prop",
        "PRODUCT_QUANTITY_VARIABLE" => "quantity",
        "PRODUCT_SUBSCRIPTION" => "N",
        "PROPERTY_CODE_10" => array("",""),
        "PROPERTY_CODE_11" => array("",""),
        "PROPERTY_CODE_12" => array("",""),
        "SHOW_DISCOUNT_PERCENT" => "N",
        "SHOW_IMAGE" => "Y",
        "SHOW_NAME" => "Y",
        "SHOW_OLD_PRICE" => "N",
        "SHOW_PRICE_COUNT" => "1",
        "TEMPLATE_THEME" => "blue",
        "USE_PRODUCT_QUANTITY" => "N"
    )
);?>