CREATE TABLE `corsik_yadelivery_zones`
(
  ID INT NOT NULL AUTO_INCREMENT,
  ACTIVE CHAR(1) NOT NULL DEFAULT 'Y',
  SORT INT(11) NOT NULL DEFAULT '500',
  NAME VARCHAR(255) NOT NULL,
  COORDINATES LONGTEXT NOT NULL,
  SITE_ID CHAR(2),
  PRIMARY KEY (ID)
);

CREATE TABLE `corsik_yadelivery_warehouses`
(
    ID INT NOT NULL AUTO_INCREMENT,
    ACTIVE CHAR(1) NOT NULL DEFAULT 'Y',
    SORT INT(11) NOT NULL DEFAULT '500',
    NAME VARCHAR(255) NOT NULL,
    ZONE_ID CHAR(2),
    COORDINATES LONGTEXT NOT NULL,
    SITE_ID CHAR(2),
    PRIMARY KEY (ID)
);

CREATE TABLE `corsik_yadelivery_rules`
(
    ID INT NOT NULL AUTO_INCREMENT,
    ACTIVE CHAR(1) NOT NULL DEFAULT 'Y',
    SORT INT(11) NOT NULL DEFAULT '500',
    NAME VARCHAR(255) NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    RULE TEXT NOT NULL,
    SITE_ID CHAR(2),
    PRIMARY KEY (ID)
);